#!/bin/bash

echo -n "Siesesta kuu number: "; read kuu

if [ $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 ]; then
	echo "Antud kuul on talv"
elif [ $kuu -ge 3 -a $kuu -le 5 ]; then
	echo "Antud kuul on kevad"
elif [ $kuu -ge 6 -a $kuu -le 8 ]; then
	echo "Antud kuul on suvi"
elif [ $kuu- -ge 9 -a $kuu -le 11 ]; then
	echo "Antud kuul on sygis"
else
	echo "Antud kuu numbrit pole, sisestaga kuu number [0-12]"
fi
