#!/bin/bash

echo -n "Millise kataloogi kohta soovite informatsiooni?: "; read directory
names=$(ls -l $directory | awk '{if(NR>1)print $9}')
types=$(ls -l $directory | awk '{if(NR>1)print substr ($0, 0, 2)}')
num=1

for type in $types; do
	if [ $type == '-' ]; then
		echo -n 'fail: '
	elif [ $type == 'd' ]; then
		echo -n 'kaust: '
	elif [ $type == 'l' ]; then
		echo -n 'link: '
	fi
	echo $names | cut -d ' ' -f$num
	let num++
done
