#!/bin/bash

aeg=$(date +%H)
kasutaja=$(whoami)

if [ $aeg -ge 6 -a $aeg -le 11 ]; then
	echo "Tere hommikust, $kasutaja!"
elif [ $aeg -ge 12 -a $aeg -le 17 ]; then
	echo "Tere paevast, $kasutaja!"
elif [ $aeg -ge 18 -a $aeg -le 21 ]; then
	echo "Tere ohtust, $kasutaja!"
elif [ $aeg -ge 22 -a $aeg -le 24 ] || [ $aeg -ge 0 -a $aeg -le 5 ]; then
	echo "Head ood, $kasutaja!"
else
	echo "Sisestage aeg väärtuses 0-24"
fi
