#!/bin/bash
#Skript küsib kasutaja ees ja perekonna nime ja esitab selle
tervitus() {
	echo "Mis on sinu ees ja perekonna nimi?"
	read eesnimi perenimi 
	echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"
}

tervitus
